version: '3.8'

services:
  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/public:/var/www/public
    depends_on:
      - frontend
      - backend

  frontend:
    build: ./frontend
    container_name: libris_frontend

  backend:
    build: ./backend
    container_name: libris_backend
    volumes:
      - ./backend:/var/www
      - /var/www/vendor  # <--- ESTA ES LA LÃNEA NUEVA
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: libris_db
      DB_USERNAME: libris_user
      DB_PASSWORD: libris_password
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: libris_db
    restart: always
    environment:
      MYSQL_DATABASE: libris_db
      MYSQL_USER: libris_user
      MYSQL_PASSWORD: libris_password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: